### ISSUE TITLE
Automa CEB : Failed to fetch

### ISSUE THREAD

**Issue by sunnmagic** [AutomaApp/automa#1425]
Hi,

I've just updated an extension this morning after Automa 1.28.15 update, and the extension doesn't work anymore, the "running workflows" window disappear, the workflow seems to run, but there is an error: "Type error: Failed to fetch", as you can see on this video: https://www.loom.com/share/5103f8ade36f427f8869356ad730bf2d

The workflow itself works fine, only the Automa CEB version doesn't work.

**Comment by Raisrahman37** [comment]
Yes, I also experienced it

**Comment by Kholid060** [comment]
> the "running workflows" window disappear

The popup will automatically close when there's no workflow running.

> the workflow seems to run, but there is an error: "Type error: Failed to fetch"

I'm not quite sure what the cause of this error is. Do you have a workflow file that I can use to reproduce this issue?

**Comment by sunnmagic** [comment]
@Kholid060, actually, the popup workflow disappears but the workflow is running (you have the "1" blue number on the extension's icon).

Can I send you the needed workflow and data in a private way?

**Comment by sunnmagic** [comment]
Done ;)

**Comment by Raisrahman37** [comment]
@Kholid060 I also experienced the same case. At start, the workflow is always closed.

**Comment by Raisrahman37** [comment]
> > @Kholid060, actually, the popup workflow disappears but the workflow is running (you have the "1" blue number on the extension's icon).
> > 
> > Can I send you the needed workflow and data in a private way?
> 
> Sure, you can email me at kholid060@gmai.com

I have also sent it in Email. Please check it out I have also sent it in Email. Please check it out, sir 🙏

**Comment by Kholid060** [comment]
Fixed

**Comment by sunnmagic** [comment]
Hi @Kholid060,

I still have the same issue, do I have to recreate the extension? What do I have to do to see this error disappear?

**Comment by Raisrahman37** [comment]
> Hi @Kholid060,
> 
> I still have the same issue, do I have to recreate the extension? What do I have to do to see this error disappear?

The problem has been found @sunnmagic If the workflow uses a block condition it will go to Close, without a block condition will appear.
