### ISSUE TITLE
Automa CEB Extension Doesnt Look Like What is Shown on Customize Page

### ISSUE THREAD

**Issue by Delusionnnn** [AutomaApp/automa#1463]
**Describe the bug**
Autome CEB customize look does not equal what the extension looks like after publishing and installing.

**Expected behavior**
What used to happen a couple of patches ago where it cuts it off at the lowest point of your customize and doesnt have this odd scroll bar with reference to the automa version wayyyy below. Also it resizes some of the buttons sometimes.

**Screenshots**

What is looks like on website:
![image](https://github.com/AutomaApp/automa/assets/141815049/ddb4b519-dbba-42dc-a84e-c47a96603b08)

What is looks like after insalling: 

![image](https://github.com/AutomaApp/automa/assets/141815049/ee850623-2574-41ff-8f52-df600a48443f)
![image](https://github.com/AutomaApp/automa/assets/141815049/01457d68-2c3d-44ec-9c77-f94c94a74a31)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [Google Chrome]
 - Extension Version: 1.28.16

**Comment by Kholid060** [comment]
Fixed

**Comment by Delusionnnn** [comment]
This is still happening after repacking, but it has improved some. 

![image](https://github.com/AutomaApp/automa/assets/141815049/cb1a6762-4fb6-4ca5-a08b-91abef96f655)
![image](https://github.com/AutomaApp/automa/assets/141815049/d3911122-3f1a-4c4d-900b-20bb3b8f7363)

**Comment by Delusionnnn** [comment]
> Fixed

Just though i'd say this is still happening. Not sure if you know or not.
