### ISSUE TITLE
Automa CEB: "Execute Workflow" block doesn't work

### ISSUE THREAD

**Issue by sunnmagic** [AutomaApp/automa#1484]
Hi,

The "Execute Workflow" block doesn't work in an extension created by Automa CEB (it works in a regular workflow). Here are the errors:

![image](https://github.com/AutomaApp/automa/assets/50998197/bf8b6a86-249a-4966-8679-fc12457e9a18)

**Comment by Kholid060** [comment]
Fixed, but you need to re-add the workflows.

**Comment by sunnmagic** [comment]
Still the same issue unfortunately:

![image](https://github.com/AutomaApp/automa/assets/50998197/ec6d700c-e1c5-410d-8183-ee696116e48b)

**Comment by Kholid060** [comment]
It should be fixed now

**Comment by sunnmagic** [comment]
Still not unfortunately... despite deleting then re-importing workflows:

![image](https://github.com/AutomaApp/automa/assets/50998197/669e64c7-a92e-4894-8983-74ae61dfd8e1)

**Comment by sunnmagic** [comment]
Hi,

Do you have news about this issue?

**Comment by sunnmagic** [comment]
Hello Kholid,

First of all, I hope you're well.

Can you tell me if anyone is still working on the Automa project?

If this is no longer the case, what will become of it? Who owns it?

Thanks in advance!

Mikael Buxton
